### PR TITLE
[_AtomicShims] On Darwin, ensure we link against libswiftCore using assembly shenanigans

### LINKED ISSUE #55: import Atomics won't compile in Playgrounds
I am trying to import swift-atomics into a Playground.  This fails to compile the shims because Playgrounds don't (and as far as I can tell, won't) link `libswiftCore.dylib`.  This is similar to [Issue #8](https://github.com/apple/swift-atomics/issues/8) in that its dying in the same place, unfortunately the work arounds don't work here.  There is mention of using Unmanaged to do this in: [SR-13708](https://github.com/apple/swift/issues/56105#issuecomment-1108432536). 

Given that the only use of these two functions is in:
```
extension Unmanaged {
  internal func retain(by delta: Int) {
    _sa_retain_n(toOpaque(), UInt32(delta))
  }

  internal func release(by delta: Int) {
    _sa_release_n(toOpaque(), UInt32(delta))
  }
}
```
I've been giving thought to trying to replace `_sa_retain_n(void *object, uint32_t n)` and `void _sa_release_n(void *object, uint32_t n)` with Swift versions that do what the comment in SR13708 suggests, but wanted to check and 1) see if that is actually advisable and 2) ask why the comment:

"Looping over Unmanaged.retain/release doesn't seem like a viable option, although I'm sure that would work too."

indicates both that it "doesn't seem viable" and "would work too" .

### Information

- **Package version:** 1.0.2
- **Platform version:** MacOS 12
- **Swift version:** swift-driver version: 1.62.1 Apple Swift version 5.7 (swiftlang-5.7.0.123.7 clang-1400.0.29.50)
Target: arm64-apple-macosx12.0

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] I've searched for [existing reports](https://github.com/apple/swift-atomics/issues) of the same issue.

### Steps to Reproduce
git clone https://github.com/CSCIX65G/AtomicsExample/tree/main/Sources/AtomicsExample, try to run the Playground

### Expected behavior
The playground should compile and run.

### Actual behavior
The playground fails to compile

### PR DESCRIPTION
**Pull request by lorentey**
Like #95 and #96, the intention here is to avoid a linker failure when the build system decides to build this module as a standalone library.

Hopefully this will all go away soon, when swift_retain_n/swift_release_n will become primitives exposed by the stdlib.

Resolves #55 

### Checklist
- [X] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-atomics)
- [X] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [X] I've followed the coding style of the rest of the project.
- [ ] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [X] I've verified that my change does not break any existing tests.
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
Local testing confirms that this resolves the issue that's plaguing #55 (and rdar://108390931).

**Comment by lorentey** [comment]
> Local testing confirms that this resolves the issue that's plaguing https://github.com/apple/swift-atomics/issues/55 (and rdar://108390931).

Not so fast! It looks like the method I'm using to override the swift-atomics release tag with a local checkout also resolves it, by itself. Grr.

File: Sources/_AtomicsShims/src/_AtomicsShims.c [hunk 1]
```diff
@@ -16,6 +16,14 @@
 // like calls to swift_retain_n/swift_release_n appearing in Swift code, not
 // even when imported through C. (See https://bugs.swift.org/browse/SR-13708)
 
+#if defined(__APPLE__) && defined(__MACH__)
+// Ensure we link with libswiftCore.dylib even when the build system decides
+// to build this module as a standalone library.
+// (See https://github.com/apple/swift-atomics/issues/55)
+__asm__(".linker_option \"-L/usr/lib/swift\"\n");
```
Comment (lorentey) [inline Sources/_AtomicsShims/src/_AtomicsShims.c:23]: Ah, `-L` doesn't actually work, but (for some reason) it also seems unnecessary, at least on 5.9.

**Comment by lorentey** [comment]
@swift-ci test

**Review by glessard — APPROVED** [review]

**Comment by rvsrvs** [comment]
@lorentey does Swift 5.9 expose `swift_retain_n` and `swift_release_n`?  Thinking this would fix all my problems with playgrounds!
